ci: Fix build by disabling Windows/Qt5 combo
Qt 5 doesn't build anymore with MSVC, since MSVC removed some symbols.
(qvector.h(960): error C2653: 'stdext': is not a class or namespace
name)

I'd be happy to just remove all Qt5 from CI, but let's still leave
the ubuntu one for some Qt5 coverage, since it hasn't rotten yet.